const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process');
const C=require('../site/assets/core.js'),W=require('../site/assets/workflows.js'),A=require('../site/assets/ansible.js');
const profiles=['26.5.260807','26.6.260925'].map(id=>require('../profiles/'+id+'.json'));
function example(profile=profiles[1]){const p=W.exampleProject(profile.id,'patch');p.jobs[0].context={os:'linux',topology:'single',tde:'none'};p.automation={host:'lab.example.com'};return p;}
for(const f of profiles)test('Ansible package preserves the exact selected build and original configuration: '+f.id,async()=>{
  const p=example(f),files=await A.bundle(p,f),get=n=>files.find(a=>a.name===n)?.content,plan=JSON.parse(get('files/plan.json'));
  assert.equal(plan.profile,f.id);assert.equal(plan.jar_sha256,f.jarSha256);assert.equal(plan.resume_cli,!!f.behavior.resumeCli);
  assert.equal(get('files/autoupgrade.cfg'),C.renderConfig(p));assert.equal(plan.config_sha256,crypto.createHash('sha256').update(C.renderConfig(p)).digest('hex'));
  for(const name of ['prepare.yml','analyze.yml','deploy.yml','verify.yml','test-local.yml','README.md','files/runner.py','tests/simulator.py'])assert(get(name),name);
  assert(!files.some(a=>a.name.endsWith('.jar')));assert(!get('deploy.yml').includes('restore -'));
});
test('pinned RU is retained for inventory verification',async()=>{const p=example();p.jobs[0].values.patch='RU:19.28,OPATCH';const files=await A.bundle(p,profiles[1]);assert.equal(JSON.parse(files.find(f=>f.name==='files/plan.json').content).pinned_ru,'19.28');});
for(const [name,mutate] of [
  ['missing host',p=>delete p.automation.host],['missing explicit topology',p=>delete p.jobs[0].context.topology],['RAC',p=>p.jobs[0].context.topology='rac'],['RAC One Node',p=>p.jobs[0].context.topology='racone'],['SEHA',p=>p.jobs[0].context.topology='seha'],['Data Guard primary',p=>p.jobs[0].context.role='primary_dg'],['standby',p=>p.jobs[0].context.role='standby'],['Windows',p=>p.jobs[0].context.os='windows'],['remote source',p=>p.jobs[0].context.location='remote'],['multiple databases',p=>p.jobs.push(C.clone(p.jobs[0]))],['password wallet',p=>p.execution={autologin:'NO'}],['password TDE',p=>p.jobs[0].context.tde='password'],['internal settings',p=>p.execution={settingsPath:'/tmp/settings'}],['WAIT drain',p=>p.jobs[0].values.drain_timeout='WAIT'],['scheduled database stage',p=>p.jobs[0].values.start_time='+1h'],['same homes',p=>p.jobs[0].values.target_home=p.jobs[0].values.source_home],['missing logs',p=>delete p.globals.global_log_dir],['parent traversal',p=>p.automation.workDir='/tmp/../oracle'],['Jinja path',p=>p.automation.workDir='/tmp/{{ lookup("pipe", "id") }}'],['host line injection',p=>p.automation.host='lab\nother: evil'],['invalid timeout',p=>p.automation.timeout='0'],['invalid poll',p=>p.automation.poll='0']
])test('Ansible blocks '+name,async()=>{const p=example();mutate(p);assert.equal(A.assess(p,profiles[1]).ready,false);await assert.rejects(A.bundle(p,profiles[1]));});
test('upgrade and software preparation are outside the existing-database export',()=>{for(const scenario of ['upgrade','install','download','gold_use']){const p=W.exampleProject(profiles[1].id,scenario);assert(!A.assess(p,profiles[1]).ready);}});
test('non-Linux media cannot be deployed to the Linux execution host',()=>{const p=example();p.jobs[0].values.platform='WINDOWS.X64';assert(!A.assess(p,profiles[1]).ready);});
test('saved projects round-trip Ansible settings and reject malformed maps',()=>{const p=example();assert.deepEqual(C.loadProject(JSON.stringify(p),{[profiles[1].id]:profiles[1]}),p);p.automation=[];assert.throws(()=>C.loadProject(JSON.stringify(p),{[profiles[1].id]:profiles[1]}));});
test('literal paths retain spaces, quotes and shell metacharacters without shell execution',async()=>{const p=example();p.automation.workDir="/tmp/Oracle's home $(id)";p.execution={javaPath:"/tmp/Java's bin/java"};const files=await A.bundle(p,profiles[1]);const plan=JSON.parse(files.find(f=>f.name==='files/plan.json').content);assert.equal(plan.java,p.execution.javaPath);assert.equal(plan.jar,p.automation.workDir+'/autoupgrade.jar');assert(files.find(f=>f.name==='host_vars/oracle_db.yml').content.includes('!unsafe'));assert(files.find(f=>f.name==='tasks/run.yml').content.includes('expand_argument_vars: false'));});
test('SSH and software owner settings select sudo only when needed',async()=>{const p=example();let files=await A.bundle(p,profiles[1]);assert(files.find(f=>f.name==='host_vars/oracle_db.yml').content.includes('alis_become: false'));p.automation.sshUser='ansible';files=await A.bundle(p,profiles[1]);assert(files.find(f=>f.name==='host_vars/oracle_db.yml').content.includes('alis_become: true'));});
test('ZIP interoperates with Python zipfile, preserves UTF-8 and CRCs, and is deterministic',()=>{
  const files=[{name:'README.md',content:'Zażółć gęślą jaźń\n'},{name:'files/a.cfg',content:'x=1\n'}],bytes=A.zip(files);
  assert.deepEqual(A.zip(files),bytes);const directory=fs.mkdtempSync(path.join(os.tmpdir(),'alis-zip-'));
  try{const archive=path.join(directory,'output.zip');fs.writeFileSync(archive,bytes);const result=cp.spawnSync('python3',['-S','-c','import zipfile,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; assert z.read("alis-ansible/README.md").decode()=="Zażółć gęślą jaźń\\n"; assert len(z.namelist())==2',archive],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);}finally{fs.rmSync(directory,{recursive:true,force:true});}
});
test('ZIP rejects duplicate and escaping paths',()=>{for(const name of ['../evil','/absolute','files/../../evil'])assert.throws(()=>A.zip([{name,content:''}]));assert.throws(()=>A.zip([{name:'a',content:''},{name:'a',content:''}]));assert.equal(A.crc32(new TextEncoder().encode('123456789')),0xcbf43926);});
