const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const C=require('../site/assets/core.js');
const profile=JSON.parse(fs.readFileSync(path.join(__dirname,'../profiles/26.5.260807.json'),'utf8'));
const profiles={[profile.id]:profile};
const fresh=()=>{const p=C.newProject(profile.id);p.globals.global_log_dir='/u01/au/logs';p.jobs[0].values={sid:'ORCL',source_home:'/u01/db19',target_version:'26'};return p;};
const errors=p=>C.validate(p,profile).filter(i=>i.level==='error');
const has=(p,code)=>C.validate(p,profile).some(i=>i.code===code);

test('minimal analyze uses target version without target home',()=>assert.deepEqual(errors(fresh()),[]));
test('empty new project cannot be exported',()=>assert.equal(errors(C.newProject(profile.id)).length,3));
test('deploy requires target home',()=>{const p=fresh();p.mode='deploy';assert(has(p,'required'));p.jobs[0].values.target_home='/u01/db26';assert.equal(errors(p).length,0);});
test('source home can be omitted for upgrade mode',()=>{const p=fresh();p.mode='upgrade';delete p.jobs[0].values.source_home;p.jobs[0].values.target_home='/u01/db26';assert.equal(errors(p).length,0);});
test('analyze requires home when target version is absent',()=>{const p=fresh();delete p.jobs[0].values.target_version;assert(has(p,'required'));});
test('global values inherit and local values override',()=>{const p=fresh();p.globals.restoration='NO';assert.equal(C.effective(p,p.jobs[0],'restoration',profile).value,'NO');p.jobs[0].values.restoration='YES';assert.equal(C.effective(p,p.jobs[0],'restoration',profile).source,'Local setting');});
test('global actions do not become local actions',()=>{const p=fresh();p.globals.before_action='/u01/global.sh';assert.equal(C.effective(p,p.jobs[0],'before_action',profile).value,null);assert(C.renderConfig(p).includes('global.before_action='));});
test('COMPATIBLE increase requires GRP removal',()=>{const p=fresh();p.jobs[0].values.raise_compatible='YES';assert(has(p,'grp'));p.globals.drop_grp_after_upgrade='YES';assert(!has(p,'grp'));assert(has(p,'raise'));});
test('explicit COMPATIBLE version is accepted',()=>{const p=fresh();p.jobs[0].values={...p.jobs[0].values,target_version:'23.4',raise_compatible:'23.4',drop_grp_after_upgrade:'YES'};assert.equal(errors(p).length,0);});
test('COMPATIBLE cannot exceed a specified target RU',()=>{const p=fresh();Object.assign(p.jobs[0].values,{target_version:'23.4',raise_compatible:'23.7',drop_grp_after_upgrade:'YES'});assert(has(p,'compatible-release'));});
test('COMPATIBLE must have the same major release',()=>{const p=fresh();Object.assign(p.jobs[0].values,{raise_compatible:'19',drop_grp_after_upgrade:'YES'});assert(has(p,'compatible-release'));});
test('unsupported target version is detected',()=>{const p=fresh();p.jobs[0].values.target_version='99';assert(has(p,'target-version'));});
test('Replay requires target 21+',()=>{const p=fresh();Object.assign(p.jobs[0].values,{target_version:'19',replay:'YES'});assert(has(p,'replay'));});
test('timezone is not represented by a guessed constant default',()=>assert.equal(C.effective(fresh(),fresh().jobs[0],'timezone_upg',profile).value,null));
test('timezone rejects arbitrary strings',()=>{const p=fresh();p.jobs[0].values.timezone_upg='MAYBE';assert(has(p,'value'));});
test('local-only parameters cannot be global',()=>{const p=fresh();p.globals.sid='ORCL';assert(has(p,'scope'));});
test('global-only parameters cannot be local',()=>{const p=fresh();p.jobs[0].values.keystore='/u01/wallet';assert(has(p,'scope'));});
test('both log aliases are rejected',()=>{const p=fresh();p.globals.autoupg_log_dir='/tmp/other';assert(has(p,'logs'));});
test('unknown parameters survive with a warning',()=>{const p=fresh();p.jobs[0].values.future_option='YES';assert.equal(errors(p).length,0);assert(has(p,'unknown'));assert(C.renderConfig(p).includes('future_option=YES'));});
test('known parameters for the other operation are errors',()=>{const p=fresh();p.jobs[0].values.method='OUTOFPLACE';assert(has(p,'operation'));});
test('unregistered LDAP option does not claim support',()=>{const p=fresh();p.jobs[0].values.target_ldap_admin_dir='/u01/network';assert(has(p,'unsupported'));});
test('patch media folder is required',()=>{const p=fresh();p.operation='patch';p.jobs[0].scenario='patch';assert(has(p,'required'));p.jobs[0].values.download_folder='/u01/stage';assert.equal(errors(p).length,0);});
test('patch unsupported options are rejected',()=>{const p=fresh();p.operation='patch';p.jobs[0].scenario='patch';p.jobs[0].values.download_folder='/u01/stage';for(const name of ['proxy-server','ssh-server','ignore_conflicts','datapatch_options']){p.jobs[0].values[name]='YES';assert(has(p,'unsupported'));delete p.jobs[0].values[name];}});
test('patch method and availability enforce fixed enums',()=>{const p=fresh();p.operation='patch';p.jobs[0].scenario='patch';p.jobs[0].values.method='INPLACE';assert(has(p,'value'));delete p.jobs[0].values.method;p.jobs[0].values.db_availability='ONLINE';assert(has(p,'value'));});
test('patch download does not require source/target home',()=>{const p=fresh();p.operation='patch';p.mode='download';p.jobs[0].scenario='patch';delete p.jobs[0].values.source_home;p.jobs[0].values.download_folder='/u01/stage';assert.equal(errors(p).length,0);});
test('nested PDB settings retain exact parameter identity',()=>{const text='upg1.sid=CDBOLD\nupg1.target_cdb=CDBNEW\nupg1.pdbs=SALES,HR\nupg1.target_pdb_name.SALES=SALES_NEW\n';const {project:p}=C.parseConfig(text,profile);assert.equal(p.jobs[0].pdb.sales.target_pdb_name,'SALES_NEW');assert.equal(C.renderConfig(p),text);});
test('patch keys with multiple dots are not PDB suffixes',()=>{const text='patch1.sid=ORCL\npatch1.home_settings.binopt.rac=YES\n';const p=C.parseConfig(text,profile,'patch').project;assert.equal(p.jobs[0].values['home_settings.binopt.rac'],'YES');assert.equal(C.renderConfig(p),text);});
test('duplicate keys including case variants block export',()=>{for(const value of ['ORCL','OTHER']){const p=C.parseConfig('upg1.sid=ORCL\nUPG1.SID='+value+'\n',profile).project;assert(has(p,'duplicate'));}});
test('empty values are diagnosed rather than silently omitted',()=>{const p=C.parseConfig('upg1.sid=\n',profile).project;assert(has(p,'syntax'));});
test('double-quoted paths are diagnosed',()=>{const p=fresh();p.jobs[0].values.source_home='"/u01/db19"';assert(has(p,'syntax'));});
test('non-ASCII and line injection are rejected',()=>{for(const value of ['/u01/żółć','ORCL\nupg1.restoration=NO','/tmp/a;id']){const p=fresh();p.jobs[0].values.sid=value;assert(has(p,'syntax'));}});
test('comments, order and unknown entries survive an unchanged import',()=>{const text='# Header\n\nUPG1.SID=ORCL # source\nupg1.future=yes\n';const p=C.parseConfig(text,profile).project;assert.equal(C.renderConfig(p),text);});
test('changing imported values preserves inline comments',()=>{const p=C.parseConfig('UPG1.SID=ORCL # source\n',profile).project;p.jobs[0].values.sid='NEWDB';assert.equal(C.renderConfig(p),'upg1.sid=NEWDB # source\n');});
test('removing imported fields removes their assignment',()=>{const p=C.parseConfig('# Header\nupg1.sid=ORCL\nupg1.log_dir=/tmp/log\n',profile).project;delete p.jobs[0].values.log_dir;assert(!C.renderConfig(p).includes('log_dir'));});
test('malformed lines are retained and diagnosed',()=>{const p=C.parseConfig('upg1.sid=ORCL\nthis is not an assignment\n',profile).project;assert(has(p,'import-line'));assert(C.renderConfig(p).includes('this is not an assignment'));});
test('import rejects prototype keys without polluting objects',()=>{const p=C.parseConfig('upg1.sid=ORCL\nupg1.target_pdb_name.__proto__=evil\n',profile).project;assert(has(p,'import-line'));assert.equal({}.evil,undefined);});
test('PDB migration requires a target and PDB selection',()=>{const p=fresh();p.jobs[0].scenario='unplug';assert(errors(p).filter(i=>i.code==='required').length===2);});
test('many PDBs reject ambiguous unsuffixed values',()=>{const p=fresh();p.jobs[0].scenario='unplug';Object.assign(p.jobs[0].values,{target_cdb:'NEWCDB',pdbs:'SALES,HR',target_pdb_name:'NEW'});assert(has(p,'nested'));});
test('preserving unplugged PDB requires COPY',()=>{const p=fresh();p.jobs[0].scenario='unplug';Object.assign(p.jobs[0].values,{target_cdb:'NEWCDB',pdbs:'SALES'});p.jobs[0].pdb.sales={keep_source_pdb:'YES'};assert(has(p,'copy'));p.jobs[0].pdb.sales.target_pdb_copy_option='file_name_convert=none';assert(!has(p,'copy'));});
test('refreshable mapping requires database links and intervals',()=>{const p=fresh();p.jobs[0].scenario='refreshable';Object.assign(p.jobs[0].values,{target_cdb:'NEWCDB',pdbs:'SALES'});assert(has(p,'dblink'));p.jobs[0].pdb.sales={source_dblink:'SALES_LINK nope'};assert(has(p,'refresh-interval'));p.jobs[0].pdb.sales.source_dblink='SALES_LINK 600';assert.equal(errors(p).length,0);});
test('orphan and duplicate PDB entries are diagnosed',()=>{const p=fresh();p.jobs[0].scenario='unplug';Object.assign(p.jobs[0].values,{target_cdb:'NEWCDB',pdbs:'SALES,SALES'});p.jobs[0].pdb.hr={target_pdb_name:'NEW'};assert(has(p,'duplicate-pdb'));assert(has(p,'orphan-pdb'));});
test('cross-job PDB target collisions are rejected',()=>{const p=fresh();const a=p.jobs[0];a.scenario='noncdb';Object.assign(a.values,{target_cdb:'NEWCDB',target_pdb_name:'SAME'});const b=C.clone(a);b.prefix='upg2';b.values.sid='OTHER';p.jobs.push(b);assert(has(p,'target-collision'));});
test('CDB receiving PDBs cannot be upgraded in another job',()=>{const p=fresh();const b=C.clone(p.jobs[0]);b.prefix='upg2';b.scenario='noncdb';b.values.sid='OLD';b.values.target_cdb='ORCL';p.jobs.push(b);assert(has(p,'target-upgrade'));});
test('statistic degree must agree with dictionary statistics',()=>{const p=fresh();Object.assign(p.jobs[0].values,{parallel_stats_degree:'4',dictionary_stats_before:'NO'});assert(has(p,'stats'));p.jobs[0].values.parallel_stats_degree='-1';assert(has(p,'degree'));});
test('start time validates actual calendar dates and distinct units',()=>{for(const value of ['31/02/2026 11:00:00','+1h2h','01/01/2026 25:00:00']){const p=fresh();p.jobs[0].values.start_time=value;assert(has(p,'start'));}for(const value of ['NOW','+1h30m','29/02/2028 11:00:00']){const p=fresh();p.jobs[0].values.start_time=value;assert(!has(p,'start'));}});
test('POSIX command quotes paths safely',()=>{const p=fresh();p.jarPath="/tmp/a'b.jar";assert(C.command(p).includes("'/tmp/a'\\''b.jar'"));assert(C.command(p).endsWith('-mode analyze'));});
test('project save/load round trip preserves values and text',()=>{const p=fresh();const copy=C.loadProject(JSON.stringify(p),profiles);assert.deepEqual(copy,p);assert.equal(C.renderConfig(copy),C.renderConfig(p));});
test('invalid projects fail before replacing working state',()=>{for(const value of ['null','{}','{"format":99}'])assert.throws(()=>C.loadProject(value,profiles));const p=fresh();p.jobs[0].pdb=JSON.parse('{"__proto__":{}}');assert.throws(()=>C.loadProject(JSON.stringify(p),profiles));});
test('project import does not trust injected raw records',()=>{const p=fresh();p.records=[{raw:'evil.sid=OTHER'}];const copy=C.loadProject(JSON.stringify(p),profiles);assert(!C.renderConfig(copy).includes('evil'));});
test('diff reports changed and added lines',()=>{const diff=C.diff('a=1\nb=2\n','a=1\nb=3\nc=4\n');assert(diff.includes('- b=2'));assert(diff.includes('+ b=3'));assert(diff.includes('+ c=4'));});
test('renderer returns final newline and stable repeated output',()=>{const p=fresh();assert.equal(C.renderConfig(p),C.renderConfig(p));assert(C.renderConfig(p).endsWith('\n'));});
test('all profile names and statuses are accounted for',()=>{assert.equal(profile.operations.upgrade.length,83);assert.equal(profile.operations.patch.length,89);assert.equal(profile.operations.patch.filter(p=>p.status==='unsupported').length,4);});
test('scenario changes cannot silently keep migration semantics',()=>{const p=fresh();p.jobs[0].values.target_cdb='NEWCDB';assert(has(p,'scenario-settings'));});
test('key injection from a project is diagnosed',()=>{const p=fresh();p.jobs[0].values['sid\nevil.sid']='OTHER';assert(has(p,'key'));});
test('copy preservation cannot be claimed using NOCOPY',()=>{const p=fresh();p.jobs[0].scenario='unplug';Object.assign(p.jobs[0].values,{target_cdb:'NEWCDB',pdbs:'SALES'});p.jobs[0].pdb.sales={keep_source_pdb:'YES',target_pdb_copy_option:'NOCOPY'};assert(has(p,'copy'));assert(has(p,'copy-clause'));});
