#!/usr/bin/env python3
"""Build ALIS's static profile bundle and self-contained offline edition. Stdlib only."""
from pathlib import Path
import base64
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]


def build():
    profiles = {}
    for path in sorted((ROOT / "profiles").glob("*.json")):
        profile = json.loads(path.read_text())
        if profile["id"] != path.stem:
            raise ValueError("Profile id must match filename")
        for operation in ("upgrade", "patch"):
            names = [p["name"] for p in profile["operations"][operation]]
            if len(names) != len(set(names)):
                raise ValueError("Duplicate parameter names in " + operation)
        profiles[profile["id"]] = profile
    if not profiles:
        raise ValueError("At least one profile is required")
    bundle = "/* Generated by tools/build.py; edit profiles/*.json. */\nconst ALIS_PROFILES = " + json.dumps(profiles, ensure_ascii=True, separators=(",", ":")) + ";\n"
    (ROOT / "site/assets/profiles.js").write_text(bundle)
    text = (ROOT / "site/index.html").read_text()
    style = (ROOT / "site/assets/style.css").read_text()
    text = text.replace('<link rel="stylesheet" href="assets/style.css">', '<style>' + style + '</style>')
    script_hashes = []
    for name in ("profiles.js", "core.js", "workflows.js", "app.js"):
        code = (ROOT / "site/assets" / name).read_text()
        code = re.sub(r"</script", r"<\\/script", code, flags=re.I)
        digest = base64.b64encode(hashlib.sha256(code.encode()).digest()).decode()
        script_hashes.append("'sha256-" + digest + "'")
        text = text.replace('<script defer src="assets/' + name + '"></script>', '<script>' + code + '</script>')
    # Inline scripts execute after the document exists, preserving defer behavior.
    scripts = re.findall(r"<script>.*?</script>", text, flags=re.S)
    text = re.sub(r"\s*<script>.*?</script>", "", text, flags=re.S)
    text = text.replace('</body>', '\n'.join(scripts) + '\n</body>')
    style_hash = base64.b64encode(hashlib.sha256(style.encode()).digest()).decode()
    text = text.replace("script-src 'self'", "script-src " + ' '.join(script_hashes))
    text = text.replace("style-src 'self'", "style-src 'sha256-" + style_hash + "'")
    favicon = base64.b64encode((ROOT / "site/assets/favicon.svg").read_bytes()).decode()
    text = text.replace('href="assets/favicon.svg"', 'href="data:image/svg+xml;base64,' + favicon + '"')
    text = text.replace('href="./" aria-label="ALIS home"', 'href="#workspace" aria-label="ALIS home"')
    # Offline download links are inert in the standalone edition; the current file is already portable.
    text = text.replace('href="offline.html" download="alis-offline.html"', 'href="#workspace"')
    text = text.replace('Download offline edition ↓', 'Offline edition · runs locally').replace('Offline edition ↓', 'Offline edition')
    # Text replacements above can also touch strings inside app.js. Hash the final bytes.
    final_hashes = ["'sha256-" + base64.b64encode(hashlib.sha256(code.encode()).digest()).decode() + "'" for code in re.findall(r"<script>(.*?)</script>", text, re.S)]
    text = re.sub(r"script-src [^;]+;", "script-src " + ' '.join(final_hashes) + ";", text, count=1)
    (ROOT / "site/offline.html").write_text(text)
    (ROOT / "site/.nojekyll").touch()
    print("Built", len(profiles), "profile(s); offline edition", len(text.encode()), "bytes")


if __name__ == "__main__":
    build()
